#!/usr/bin/env python3
"""
Builds src/puzzles.ts from the Lichess puzzle database (CC0).

Streams https://database.lichess.org/lichess_db_puzzle.csv.zst and stops after
enough rows -- the full file is ~250 MB and a few tens of thousands of rows are
plenty to sample from. Selection is deterministic, so re-running gives the same
set unless the upstream file changes.

The puzzles are NOT validated here: test-puzzles.mjs replays every one of them
with chess.js, the same library the app uses, so the data is certified by the
app's own engine rather than by python-chess.

Usage:  pip install zstandard && python3 scripts/fetch-puzzles.py
"""
import csv
import io
import json
import pathlib
import urllib.request

import zstandard

URL = "https://database.lichess.org/lichess_db_puzzle.csv.zst"
SCAN_ROWS = 60_000
PER_BAND = 30
BANDS = [(600, 999), (1000, 1299), (1300, 1599), (1600, 1999), (2000, 2400)]
OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "puzzles.ts"


def scan(limit: int) -> list[dict]:
    req = urllib.request.Request(URL, headers={"User-Agent": "AhaMate-build/1.0"})
    with urllib.request.urlopen(req, timeout=180) as raw:
        stream = io.TextIOWrapper(
            zstandard.ZstdDecompressor().stream_reader(raw), encoding="utf-8"
        )
        rows = []
        for row in csv.DictReader(stream):
            rows.append(row)
            if len(rows) >= limit:
                return rows
    return rows


def eligible(row: dict, low: int, high: int) -> bool:
    """Well-tested, well-liked puzzles with a solution short enough to explain."""
    plies = len(row["Moves"].split())
    return (
        low <= int(row["Rating"]) <= high
        and int(row["Popularity"]) >= 90
        and int(row["NbPlays"]) >= 1000
        # 2 = mate in one, 4 = two solver moves, 6 = three.
        and plies in ({2, 4, 6} if low < 1000 else {4, 6})
    )


def main() -> None:
    rows = scan(SCAN_ROWS)
    picked = []
    for low, high in BANDS:
        band = sorted(
            (r for r in rows if eligible(r, low, high)),
            key=lambda r: (-int(r["NbPlays"]), r["PuzzleId"]),
        )
        # Spread across the band's popularity range instead of taking the top N,
        # so the set isn't 30 variations on the same famous position.
        step = max(1, len(band) // PER_BAND)
        picked += band[::step][:PER_BAND]

    out = [
        {
            "id": r["PuzzleId"],
            "fen": r["FEN"],
            "moves": r["Moves"],
            "rating": int(r["Rating"]),
            "themes": r["Themes"].split(),
        }
        for r in sorted(picked, key=lambda r: int(r["Rating"]))
    ]
    # A .ts module rather than .json: it imports identically in Vite and in
    # plain Node (which would demand an import attribute for JSON), so the
    # test can load the very same data the app bundles.
    body = ",\n".join(json.dumps(p, separators=(",", ":")) for p in out)
    OUT.write_text(
        "// Generated by scripts/fetch-puzzles.py — do not edit by hand.\n"
        "// Source: Lichess puzzle database (CC0) — https://database.lichess.org\n"
        f"export default [\n{body},\n];\n"
    )
    print(f"wrote {len(out)} puzzles to {OUT}")


if __name__ == "__main__":
    main()
